---
#   - hosts: tag_Name_DAMPOCAuthor tag_Name_DAMPOCAuthor_ISG
    - hosts: tag_Name_DAMPOCAuthor 
      user: ubuntu
      become: true

      tasks:
      - name: Get Files to deploy
        shell:
          ls -1 /tmp/code_deploy/
        register: files
      - debug: var=files.stdout_lines

      - name: Install Packages
        shell: 
           cd /tmp/code_deploy && curl -u "{{ aem_api_user }}:{{ aem_api_password }}" -F force=true -F install=true -F file=@"{{ item }}" 'http://localhost:4502/crx/packmgr/service.jsp'
        with_items: "{{ files.stdout_lines }}"
        register: result
      - debug: var=result.stdout_lines
